### ISSUE TITLE
Ships not placeable

### ISSUE THREAD

**Issue by Hartwelg** [cs361fall2018/project-team-15#1]
I would like to be able to place ships and interact with them

**Comment by IsaacPeters** [comment]
boom got it

**Comment by PixelDotPixel** [comment]
Hey, With the ships can we impliment a setter and getter for the size? The board will use this to declair what amount of space the ship will take up. Something like getSize(){ return int size } would be marvelous.

**Comment by IsaacPeters** [comment]
We're close, but we're only able to place ships down once. Probably an issue with integration with frontend

**Comment by IsaacPeters** [comment]
I did it, we can place ships now. They work in the UI and everything, and the logic is all unit tested. Lets go
