### ISSUE TITLE
Attacks can't compile and be tested

### ISSUE THREAD

**Issue by IsaacPeters** [cs361fall2018/project-team-15#16]
Need to figure out a way to get Attacks to a state it can compile so we can test it properly

**Comment by PixelDotPixel** [comment]
I got it compiling, however it's is failing tests. Should we pull it in its current state?

**Comment by amayaevan** [comment]
Are they the tests related to attack? If so it might just be better to comment those out because it's testing functions that aren't even in the code

**Comment by amayaevan** [comment]
That's because there is no board implementation either

**Comment by IsaacPeters** [comment]
No we shouldn't pull anything into master unless we can actually test it

You can create another branch and merge it into that, so we can test it away from master if you want

**Comment by PixelDotPixel** [comment]
Yeah i think ima do that. For some reason it wont return the result. Its simply skipping that line.

**Comment by amayaevan** [comment]
Okay, we can do that then

**Comment by PixelDotPixel** [comment]
Im an idiot got it

**Comment by PixelDotPixel** [comment]
Works now

**Comment by Hartwelg** [comment]
does the attackcheck function work?

**Comment by IsaacPeters** [comment]
why don't you TEST it and find out
my dude

**Comment by PixelDotPixel** [comment]
No that one doesn't for some reason

**Comment by PixelDotPixel** [comment]
Fixed the compilation issue, and passes all tests so far.
